### ISSUE TITLE
move collectFromClasspath to core

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala-js/jsdependencies#13]
motivation: for use by other tools

please decouple `collectFromClasspath` from sbt and expose in 
https://github.com/scala-js/jsdependencies/tree/master/jsdependencies-core

currently it is baked into sbt plugin:
https://github.com/scala-js/jsdependencies/blob/master/jsdependencies-sbt-plugin/src/main/scala/org/scalajs/jsdependencies/sbtplugin/JSDependenciesPlugin.scala#L94

**Comment by sjrd** [comment]
It is in the sbt plugin because it uses concepts of sbt, namely `Attributed`. The `Attributed` is used to track the original files that participate in the result, which is then used by the sbt plugin to properly cache stuff, again using sbt concepts.

So the implementation here is inherently coupled with sbt, and cannot simply be moved to the core. Other tools should reimplement this part using their concepts for caching and navigating classpaths.

**Comment by Andrei-Pozolotin** [comment]
ok, will reimplement
