### ISSUE TITLE
question - npm packages and modules

### ISSUE THREAD

**Issue by ghost** [scala-js/jsdependencies#44]
I understand that scalajs-bundler is the future for npm packages and commonjs modules. Out of curiosity, I am trying to use jsdeps with an npm package with a set of commonjs modules spread over various directories which makes use of relative path requires and I am unsure if there is a way to work with these.

If I only reference index.js and use jsimport with that module only, then map out every module as a jsdep, will that help with the issues I am encountering with relative path requires suchs as "../dir/Module.js"? Or is the only real solution to run webpack to bundle the npm package before referencing it as a jsdep?

**Comment by sjrd** [comment]
Hello,

sbt-jsdependencies cannot deal with CommonJS modules, regardless of how they may be stored and referenced. It only works with Scripts.

---

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Gitter](https://gitter.im/scala-js/scala-js), where more than just the core developers can see and answer.

Thank you for your understanding.
