### ISSUE TITLE
Question: use @JSImport with ProvidedJS

### ISSUE THREAD

**Issue by tomsfernandez** [scala-js/jsdependencies#50]
Hi! How can I use @JSImport with a local javascript file ? When using an npm package I can just refer to the package name but I don't see how to import it when it is a local file.

I would also like to use this artifact from another scala-js project.

**Comment by sjrd** [comment]
Hello,

This looks like a question on using Scala.js, rather than a bug report. The GitHub Issues in this repo are for bug reports and feature requests only. Please ask questions [on StackOverflow](https://stackoverflow.com/questions/tagged/scala.js) or [on Discord](https://discord.com/invite/scala) (channel `#scala-js`), where more than just the core developers can see and answer.

Thank you for your understanding.
